name: 'scriptbots'
version: 0.0.1
description: Dart port of ScriptBots written originally by Andrej Karpathy
author: Bjørn Vidar Remme <bvremme@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  vector_math: '^2.0.3'

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
